set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

find_program(DORA_LOVE_ZIG_EXECUTABLE zig REQUIRED)

set(CMAKE_C_COMPILER "${DORA_LOVE_ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 cc)
set(CMAKE_CXX_COMPILER "${DORA_LOVE_ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER_ARG1 c++)

set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.sh")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.sh")
set(CMAKE_C_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.sh")
set(CMAKE_CXX_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.sh")
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.sh")
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.sh")

set(DORA_LOVE_ZIG_WINDOWS_TARGET "x86-windows-gnu")
set(CMAKE_C_FLAGS_INIT "-target ${DORA_LOVE_ZIG_WINDOWS_TARGET}")
set(CMAKE_CXX_FLAGS_INIT "-target ${DORA_LOVE_ZIG_WINDOWS_TARGET}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-target ${DORA_LOVE_ZIG_WINDOWS_TARGET}")
