local imageModule = require("love.image")
local filesystem = require("love.filesystem")
local graphics = require("love.graphics")
local system = require("love.system")

local textures = {}
local canvas
local autoCube
local autoVolume
local replacedCube
local replacedVolume
local cubeMipShader
local volumeMipShader
local replacedCubeShader
local replacedVolumeShader
local rendered = false
local rendererName

local function u32(value)
	return string.pack("<I4", value)
end

local function u64(value)
	return string.pack("<I8", value)
end

local function makeDDS(fourcc, blockSize, blocks)
	local header = "DDS "
		.. u32(124) .. u32(0x000a1007)
		.. u32(4) .. u32(4) .. u32(blockSize) .. u32(0) .. u32(3)
		.. string.rep(u32(0), 11)
		.. u32(32) .. u32(4) .. fourcc
		.. u32(0) .. u32(0) .. u32(0) .. u32(0) .. u32(0)
		.. u32(0x00401008) .. u32(0) .. u32(0) .. u32(0) .. u32(0)
	return header .. table.concat(blocks)
end

local function dxtColorBlocks()
	-- A complete 4x4, 2x2, 1x1 mip chain. Every level occupies one block;
	-- color index 0 selects opaque red, green, then blue. DXT3 uses explicit
	-- opaque alpha nibbles and DXT5 selects its first (opaque) alpha endpoint.
	local red = string.char(0x00, 0xf8, 0xe0, 0x07, 0, 0, 0, 0)
	local green = string.char(0xe0, 0x07, 0x1f, 0x00, 0, 0, 0, 0)
	local blue = string.char(0x1f, 0x00, 0x00, 0x00, 0, 0, 0, 0)
	return {red, green, blue}
end

local function makeDXT(format)
	local colors = dxtColorBlocks()
	if format == "DXT1" then
		return makeDDS(format, 8, colors)
	elseif format == "DXT3" then
		local alpha = string.rep(string.char(0xff), 8)
		return makeDDS(format, 16, {alpha .. colors[1], alpha .. colors[2], alpha .. colors[3]})
	elseif format == "DXT5" then
		local alpha = string.char(0xff, 0x00) .. string.rep("\0", 6)
		return makeDDS(format, 16, {alpha .. colors[1], alpha .. colors[2], alpha .. colors[3]})
	end
	error("unsupported test DXT format " .. tostring(format))
end

local function makeKTX(internalFormat, blocks, baseFormat, width, height)
	width = width or 4
	height = height or 4
	local header = string.char(0xab, 0x4b, 0x54, 0x58, 0x20, 0x31,
		0x31, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a)
		.. u32(0x04030201) .. u32(0) .. u32(1) .. u32(0)
		.. u32(internalFormat) .. u32(baseFormat or 0x1908)
		.. u32(width) .. u32(height) .. u32(0) .. u32(0)
		.. u32(1) .. u32(#blocks) .. u32(0)
	local levels = {}
	for index, block in ipairs(blocks) do
		levels[index] = u32(#block) .. block
	end
	return header .. table.concat(levels)
end

local function makeKTXDXT1()
	return makeKTX(0x83f1, dxtColorBlocks())
end

local function makeKTXASTC4x4()
	-- Generated deterministically from opaque red RGBA8 using the vendored
	-- astc-encoder at ASTCENC_PRE_MEDIUM. One block represents every mip.
	local red = string.char(0xfc, 0xfd, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff)
	return makeKTX(0x93b0, {red, red, red})
end

local function astcRedBlocks(width, height)
	-- ASTC void-extent opaque red block. This encoding is footprint-independent,
	-- so the same deterministic block covers every Love 11.5 ASTC block size.
	local red = string.char(0xfc, 0xfd, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff)
	local blocks = {}
	local extent = math.max(width, height)
	repeat
		blocks[#blocks + 1] = red
		extent = math.floor(extent / 2)
	until extent < 1
	return blocks
end

local function etc1RedBlocks()
	-- ETC1 individual mode: both subblocks use R=15, G=B=0 and table 0.
	-- Selector 0 adds +2, which clamps red to 255 and leaves G/B near zero.
	local red = string.char(0xff, 0x00, 0x00, 0x00, 0, 0, 0, 0)
	return {red, red, red}
end

local function makeKTXETC1()
	return makeKTX(0x8d64, etc1RedBlocks(), 0x1907)
end

local function makeKTXETC2RGB()
	-- ETC2 RGB accepts every valid ETC1 color block. Reusing the deterministic
	-- individual-mode red block therefore tests the ETC2 container/format path
	-- without depending on an external encoder.
	return makeKTX(0x9274, etc1RedBlocks(), 0x1907)
end

local function etc2RGBABlocks()
	-- EAC alpha base 255 with multiplier 0 decodes to opaque for every selector.
	local alpha = string.char(0xff, 0x00, 0, 0, 0, 0, 0, 0)
	local blocks = {}
	for index, color in ipairs(etc1RedBlocks()) do blocks[index] = alpha .. color end
	return blocks
end

local function etc2RGBA1RedBlocks()
	-- Deterministic opaque-red ETC2 RGB8A1 block generated by Xcode 18's
	-- TextureConverter 4.0 ETC2COMP backend at Highest quality.
	local red = string.char(0xfb, 0x00, 0xf0, 0x02, 0xff, 0xff, 0xff, 0xff)
	return {red, red, red}
end

local function makeKTXETC2RGBA()
	return makeKTX(0x9278, etc2RGBABlocks(), 0x1908)
end

local function makeKTXETC2RGBA1()
	return makeKTX(0x9276, etc2RGBA1RedBlocks(), 0x1907)
end

local function eacBlocks(channels, signed)
	-- Maximum positive EAC base codeword, multiplier 15, table 0, selector 7.
	-- This clamps every texel to +1 in both unsigned and signed formats. RG11
	-- stores two independent channel blocks in R, G order.
	local channel = string.char(signed and 0x7f or 0xff, 0xf0,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff)
	local block = channels == 2 and channel .. channel or channel
	return {block, block, block}
end

local function pvrtcRedBlocks(bitsPerPixel)
	-- Xcode 18 TextureConverter 4.0 PVRTC backend, Highest quality, opaque
	-- 8x8 red input. PVRTC keeps a 2x2-block minimum: 2bpp textures therefore
	-- has a 16x8 storage minimum while 4bpp has an 8x8 storage minimum, but both
	-- retain the source's 8x8 logical dimensions. Every mip payload is 32 bytes.
	local block = bitsPerPixel == 2
		and string.char(0x54, 0x55, 0x55, 0x55, 0x01, 0xfc, 0x00, 0xf8)
		or string.char(0x55, 0x55, 0x55, 0x55, 0x00, 0xfc, 0x00, 0xf8)
	local level = string.rep(block, 4)
	if bitsPerPixel == 2 then
		-- The 16x16 base level uses eight twiddled blocks. Lower levels use the
		-- same 32-byte minimum payload as the Xcode-generated reference.
		local base = string.char(
			0x54, 0x14, 0x10, 0x14, 0x01, 0xfc, 0x00, 0xf8,
			0x54, 0x55, 0x55, 0x55, 0x01, 0xfc, 0x00, 0xf8,
			0x01, 0x00, 0x10, 0x00, 0x01, 0xf8, 0x00, 0xf8,
			0x00, 0x00, 0x55, 0x00, 0x01, 0xfc, 0x00, 0xf8,
			0x54, 0x14, 0x10, 0x14, 0x01, 0xfc, 0x00, 0xf8,
			0x54, 0x55, 0x55, 0x55, 0x01, 0xfc, 0x00, 0xf8,
			0x01, 0x00, 0x10, 0x00, 0x01, 0xf8, 0x00, 0xf8,
			0x00, 0x00, 0x55, 0x00, 0x01, 0xfc, 0x00, 0xf8)
		return {base, level, level, level, level}
	end
	return {level, level, level, level}
end

local function makePVR(pixelFormat, blocks, width, height, channelType)
	width = width or 4
	height = height or 4
	return "PVR" .. string.char(3) .. u32(0) .. u64(pixelFormat)
		.. u32(0) .. u32(channelType or 0) .. u32(height) .. u32(width) .. u32(1)
		.. u32(1) .. u32(1) .. u32(#blocks) .. u32(0)
		.. table.concat(blocks)
end

local function assertPixel(image, x, y, expected, label)
	local red, green, blue, alpha = image:getPixel(x, y)
	assert(math.abs(red - expected[1]) < 0.04
		and math.abs(green - expected[2]) < 0.04
		and math.abs(blue - expected[3]) < 0.04 and alpha > 0.96,
		label .. ": " .. red .. "," .. green .. "," .. blue .. "," .. alpha)
end

function love.load()
	local encoded = makeDXT("DXT1")
	local file = filesystem.newFileData(encoded, "embedded.dds")
	local decoded, data = pcall(imageModule.newCompressedData, file)
	assert(decoded, data)
	assert(imageModule.isCompressed(file))
	local width, height = data:getDimensions()
	assert(width == 4 and height == 4)
	assert(data:getMipmapCount() == 3 and data:getFormat() == "DXT1")
	local mip2Width, mip2Height = data:getDimensions(2)
	local mip3Width, mip3Height = data:getDimensions(3)
	assert(mip2Width == 2 and mip2Height == 2 and mip3Width == 1 and mip3Height == 1)
	assert(data:getSize() == 24 and #data:getString() == 24)
	assert(data:typeOf("CompressedImageData") and data:typeOf("Data"))
	assert(data:clone():getString() == data:getString())
	assert(not imageModule.isCompressed(filesystem.newFileData("not compressed", "plain.bin")))
	local baseTexture = graphics.newImage(data)
	assert(baseTexture:getWidth() == 4 and baseTexture:getHeight() == 4)
	textures[1] = graphics.newImage(data, {mipmaps = true})
	assert(textures[1]:getWidth() == 4 and textures[1]:getHeight() == 4)
	for index, format in ipairs({"DXT3", "DXT5"}) do
		local sibling = imageModule.newCompressedData(
			filesystem.newFileData(makeDXT(format), "embedded-" .. format .. ".dds"))
		assert(sibling:getFormat() == format and sibling:getMipmapCount() == 3)
		assert(sibling:getSize() == 48 and #sibling:getString() == 48)
		textures[index + 1] = graphics.newImage(sibling, {mipmaps = true})
		assert(textures[index + 1]:isCompressed())
	end
	local ktxDXT1 = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXDXT1(), "embedded-DXT1.ktx"))
	assert(ktxDXT1:getFormat() == "DXT1" and ktxDXT1:getMipmapCount() == 3
		and ktxDXT1:getSize() == 24)
	textures[4] = graphics.newImage(ktxDXT1, {mipmaps = true})
	local ktxASTC = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXASTC4x4(), "embedded-ASTC4x4.ktx"))
	assert(ktxASTC:getFormat() == "ASTC4x4" and ktxASTC:getMipmapCount() == 3
		and ktxASTC:getSize() == 48)
	rendererName = graphics.getRendererInfo()
	local osName = system.getOS()
	local imageFormats = graphics.getImageFormats()
	if imageFormats.ASTC4x4 then
		textures[5] = graphics.newImage(ktxASTC, {mipmaps = true})
	else
		assert(not pcall(graphics.newImage, ktxASTC, {mipmaps = true}))
	end
	local pvrDXT1 = imageModule.newCompressedData(
		filesystem.newFileData(makePVR(7, dxtColorBlocks()), "embedded-DXT1.pvr"))
	assert(pvrDXT1:getFormat() == "DXT1" and pvrDXT1:getMipmapCount() == 3
		and pvrDXT1:getSize() == 24)
	textures[6] = graphics.newImage(pvrDXT1, {mipmaps = true})
	local ktxETC1 = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXETC1(), "embedded-ETC1.ktx"))
	local pvrETC1 = imageModule.newCompressedData(
		filesystem.newFileData(makePVR(6, etc1RedBlocks()), "embedded-ETC1.pvr"))
	for index, compressed in ipairs({ktxETC1, pvrETC1}) do
		assert(compressed:getFormat() == "ETC1" and compressed:getMipmapCount() == 3
			and compressed:getSize() == 24)
		textures[index + 6] = graphics.newImage(compressed, {mipmaps = true})
	end
	local ktxETC2 = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXETC2RGB(), "embedded-ETC2rgb.ktx"))
	assert(ktxETC2:getFormat() == "ETC2rgb" and ktxETC2:getMipmapCount() == 3
		and ktxETC2:getSize() == 24)
	if imageFormats.ETC2rgb then
		textures[9] = graphics.newImage(ktxETC2, {mipmaps = true})
	else
		assert(not pcall(graphics.newImage, ktxETC2, {mipmaps = true}))
	end
	local ktxETC2RGBA = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXETC2RGBA(), "embedded-ETC2rgba.ktx"))
	local ktxETC2RGBA1 = imageModule.newCompressedData(
		filesystem.newFileData(makeKTXETC2RGBA1(), "embedded-ETC2rgba1.ktx"))
	for index, entry in ipairs({
		{data = ktxETC2RGBA, format = "ETC2rgba", size = 48},
		{data = ktxETC2RGBA1, format = "ETC2rgba1", size = 24},
	}) do
		assert(entry.data:getFormat() == entry.format and entry.data:getMipmapCount() == 3
			and entry.data:getSize() == entry.size)
		if imageFormats[entry.format] then
			textures[index + 9] = graphics.newImage(entry.data, {mipmaps = true})
		else
			assert(not pcall(graphics.newImage, entry.data, {mipmaps = true}))
		end
	end
	local pvrETC2RGB = imageModule.newCompressedData(
		filesystem.newFileData(makePVR(22, etc1RedBlocks()), "embedded-ETC2rgb.pvr"))
	local pvrETC2RGBA = imageModule.newCompressedData(
		filesystem.newFileData(makePVR(23, etc2RGBABlocks()), "embedded-ETC2rgba.pvr"))
	local pvrETC2RGBA1 = imageModule.newCompressedData(
		filesystem.newFileData(makePVR(24, etc2RGBA1RedBlocks()), "embedded-ETC2rgba1.pvr"))
	for index, entry in ipairs({
		{data = pvrETC2RGB, format = "ETC2rgb", size = 24},
		{data = pvrETC2RGBA, format = "ETC2rgba", size = 48},
		{data = pvrETC2RGBA1, format = "ETC2rgba1", size = 24},
	}) do
		assert(entry.data:getFormat() == entry.format and entry.data:getMipmapCount() == 3
			and entry.data:getSize() == entry.size)
		if imageFormats[entry.format] then
			textures[index + 11] = graphics.newImage(entry.data, {mipmaps = true})
		else
			assert(not pcall(graphics.newImage, entry.data, {mipmaps = true}))
		end
	end
	if rendererName == "Metal" and osName == "OS X" then
		assert(textures[9] and textures[10] and not textures[11]
			and textures[12] and textures[13] and not textures[14])
	end
	local pvrtcEntries = {
		{container = "KTX", format = "PVR1rgb2", bits = 2, width = 16, height = 16, data = makeKTX(0x8c01, pvrtcRedBlocks(2), 0x1907, 16, 16)},
		{container = "KTX", format = "PVR1rgb4", bits = 4, width = 8, height = 8, data = makeKTX(0x8c00, pvrtcRedBlocks(4), 0x1907, 8, 8)},
		{container = "KTX", format = "PVR1rgba2", bits = 2, width = 16, height = 16, data = makeKTX(0x8c03, pvrtcRedBlocks(2), 0x1908, 16, 16)},
		{container = "KTX", format = "PVR1rgba4", bits = 4, width = 8, height = 8, data = makeKTX(0x8c02, pvrtcRedBlocks(4), 0x1908, 8, 8)},
		{container = "PVR", format = "PVR1rgb2", bits = 2, width = 16, height = 16, data = makePVR(0, pvrtcRedBlocks(2), 16, 16)},
		{container = "PVR", format = "PVR1rgb4", bits = 4, width = 8, height = 8, data = makePVR(2, pvrtcRedBlocks(4), 8, 8)},
		{container = "PVR", format = "PVR1rgba2", bits = 2, width = 16, height = 16, data = makePVR(1, pvrtcRedBlocks(2), 16, 16)},
		{container = "PVR", format = "PVR1rgba4", bits = 4, width = 8, height = 8, data = makePVR(3, pvrtcRedBlocks(4), 8, 8)},
	}
	for index, entry in ipairs(pvrtcEntries) do
		local compressed = imageModule.newCompressedData(filesystem.newFileData(entry.data,
			"embedded-" .. entry.format .. "." .. entry.container:lower()))
		local parsedWidth, parsedHeight = compressed:getDimensions()
		local mip2Width, mip2Height = compressed:getDimensions(2)
		local expectedMips = entry.bits == 2 and 5 or 4
		local lastMipWidth, lastMipHeight = compressed:getDimensions(expectedMips)
		local expectedSize = entry.bits == 2 and 192 or 128
		assert(compressed:getFormat() == entry.format and compressed:getMipmapCount() == expectedMips
			and parsedWidth == entry.width and parsedHeight == entry.height
			and mip2Width == entry.width / 2 and mip2Height == entry.height / 2
			and lastMipWidth == 1 and lastMipHeight == 1
			and compressed:getSize() == expectedSize,
			entry.container .. "/" .. entry.format .. ": " .. compressed:getFormat()
				.. " " .. parsedWidth .. "x" .. parsedHeight
				.. " mips=" .. compressed:getMipmapCount()
				.. " mip2=" .. mip2Width .. "x" .. mip2Height
				.. " last=" .. lastMipWidth .. "x" .. lastMipHeight
				.. " bytes=" .. compressed:getSize())
		if imageFormats[entry.format] then
			textures[index + 14] = graphics.newImage(compressed, {mipmaps = true})
		else
			assert(not pcall(graphics.newImage, compressed, {mipmaps = true}))
		end
	end
	if rendererName == "Metal" and osName == "OS X" then
		for _, index in ipairs({15, 17, 19, 21}) do assert(not textures[index]) end
		for _, index in ipairs({16, 18, 20, 22}) do assert(textures[index]) end
	end
	local astcEntries = {
		{format = "ASTC5x4", internal = 0x93b1, width = 5, height = 4},
		{format = "ASTC5x5", internal = 0x93b2, width = 5, height = 5},
		{format = "ASTC6x5", internal = 0x93b3, width = 6, height = 5},
		{format = "ASTC6x6", internal = 0x93b4, width = 6, height = 6},
		{format = "ASTC8x5", internal = 0x93b5, width = 8, height = 5},
		{format = "ASTC8x6", internal = 0x93b6, width = 8, height = 6},
		{format = "ASTC8x8", internal = 0x93b7, width = 8, height = 8},
		{format = "ASTC10x5", internal = 0x93b8, width = 10, height = 5},
		{format = "ASTC10x6", internal = 0x93b9, width = 10, height = 6},
		{format = "ASTC10x8", internal = 0x93ba, width = 10, height = 8},
		{format = "ASTC10x10", internal = 0x93bb, width = 10, height = 10},
		{format = "ASTC12x10", internal = 0x93bc, width = 12, height = 10},
		{format = "ASTC12x12", internal = 0x93bd, width = 12, height = 12},
	}
	for index, entry in ipairs(astcEntries) do
		local blocks = astcRedBlocks(entry.width, entry.height)
		local compressed = imageModule.newCompressedData(filesystem.newFileData(
			makeKTX(entry.internal, blocks, 0x1908, entry.width, entry.height),
			"embedded-" .. entry.format .. ".ktx"))
		local parsedWidth, parsedHeight = compressed:getDimensions()
		local lastWidth, lastHeight = compressed:getDimensions(#blocks)
		assert(compressed:getFormat() == entry.format
			and compressed:getMipmapCount() == #blocks
			and compressed:getSize() == #blocks * 16
			and parsedWidth == entry.width and parsedHeight == entry.height
			and lastWidth == 1 and lastHeight == 1,
			entry.format .. ": " .. parsedWidth .. "x" .. parsedHeight
				.. " mips=" .. compressed:getMipmapCount()
				.. " last=" .. lastWidth .. "x" .. lastHeight
				.. " bytes=" .. compressed:getSize())
		if imageFormats[entry.format] then
			textures[index + 22] = graphics.newImage(compressed, {mipmaps = true})
		else
			assert(not pcall(graphics.newImage, compressed, {mipmaps = true}))
		end
	end
	if rendererName == "Metal" then
		for index = 23, 35 do assert(textures[index]) end
	end
	local eacEntries = {
		{container = "KTX", format = "EACr", internal = 0x9270, channels = 1, signed = false},
		{container = "KTX", format = "EACrs", internal = 0x9271, channels = 1, signed = true},
		{container = "KTX", format = "EACrg", internal = 0x9272, channels = 2, signed = false},
		{container = "KTX", format = "EACrgs", internal = 0x9273, channels = 2, signed = true},
		{container = "PVR", format = "EACr", internal = 25, channels = 1, signed = false},
		{container = "PVR", format = "EACrs", internal = 25, channels = 1, signed = true},
		{container = "PVR", format = "EACrg", internal = 26, channels = 2, signed = false},
		{container = "PVR", format = "EACrgs", internal = 26, channels = 2, signed = true},
	}
	for index, entry in ipairs(eacEntries) do
		local blocks = eacBlocks(entry.channels, entry.signed)
		local encoded = entry.container == "KTX"
			and makeKTX(entry.internal, blocks, entry.channels == 1 and 0x1903 or 0x8227)
			or makePVR(entry.internal, blocks, 4, 4, entry.signed and 1 or 0)
		local compressed = imageModule.newCompressedData(filesystem.newFileData(encoded,
			"embedded-" .. entry.format .. "." .. entry.container:lower()))
		local mip2Width, mip2Height = compressed:getDimensions(2)
		local mip3Width, mip3Height = compressed:getDimensions(3)
		local expectedSize = entry.channels == 1 and 24 or 48
		assert(compressed:getFormat() == entry.format
			and compressed:getMipmapCount() == 3
			and compressed:getSize() == expectedSize
			and mip2Width == 2 and mip2Height == 2
			and mip3Width == 1 and mip3Height == 1,
			entry.container .. "/" .. entry.format .. " bytes=" .. compressed:getSize())
		if imageFormats[entry.format] then
			textures[index + 35] = graphics.newImage(compressed, {mipmaps = true})
		else
			assert(not pcall(graphics.newImage, compressed, {mipmaps = true}))
		end
	end
	if rendererName == "Metal" or osName == "Android" or osName == "Linux" then
		for index = 36, 43 do assert(textures[index]) end
	end
	if rendererName == "Metal" then
		assert(not pcall(graphics.newArrayImage, {data, data}, {mipmaps = true}))
		assert(not pcall(graphics.newCubeImage, {data, data, data, data, data, data}, {mipmaps = true}))
		assert(not pcall(graphics.newVolumeImage, data, {mipmaps = true}))
	else
		local compressedArray = graphics.newArrayImage({data, data}, {mipmaps = true})
		local compressedCube = graphics.newCubeImage({data, data, data, data, data, data}, {mipmaps = true})
		local compressedVolume = graphics.newVolumeImage(data, {mipmaps = true})
		assert(compressedArray:isCompressed() and compressedArray:getLayerCount() == 2
			and compressedArray:getMipmapCount() == 3)
		assert(compressedCube:isCompressed() and compressedCube:getTextureType() == "cube"
			and compressedCube:getMipmapCount() == 3)
		assert(compressedVolume:isCompressed() and compressedVolume:getTextureType() == "volume"
			and compressedVolume:getMipmapCount() == 3)
	end
	local rgba = imageModule.newImageData(4, 4)
	rgba:mapPixel(function() return 1, 0.5, 0.25, 1 end)
	local auto2d = graphics.newImage(rgba, {mipmaps = true})
	local autoArray = graphics.newArrayImage({rgba, rgba}, {mipmaps = true})
	local cubeStrip = imageModule.newImageData(24, 4)
	cubeStrip:mapPixel(function(x, y)
		if x < 4 then return (x + y) % 2, 0, (x + y + 1) % 2, 1 end
		return 0, 0, 0, 1
	end)
	autoCube = graphics.newCubeImage(cubeStrip, {mipmaps = true})
	local volumeStrip = imageModule.newImageData(8, 4)
	volumeStrip:mapPixel(function(x)
		return x < 4 and 1 or 0, 0, x < 4 and 0 or 1, 1
	end)
	autoVolume = graphics.newVolumeImage(volumeStrip, {mipmaps = true})
	assert(auto2d:getMipmapCount() == 3 and autoArray:getMipmapCount() == 3)
	assert(autoCube:getMipmapCount() == 3 and autoCube:getPixelWidth() == 4)
	assert(autoVolume:getMipmapCount() == 3 and autoVolume:getDepth() == 2
		and autoVolume:getDepth(2) == 1)
	replacedCube = graphics.newCubeImage(cubeStrip, {mipmaps = true})
	replacedVolume = graphics.newVolumeImage(volumeStrip, {mipmaps = true})
	local greenMip = imageModule.newImageData(2, 2)
	greenMip:mapPixel(function() return 0, 1, 0, 1 end)
	local yellowMip = imageModule.newImageData(2, 2)
	yellowMip:mapPixel(function() return 1, 1, 0, 1 end)
	replacedCube:replacePixels(greenMip, 1, 2, 0, 0)
	replacedVolume:replacePixels(yellowMip, 1, 2, 0, 0)
	cubeMipShader = graphics.newShader([[
#pragma language glsl3
		uniform CubeImage source;
		vec4 effect(vec4 color, Image unused, vec2 uv, vec2 screen) {
			return textureLod(source, vec3(1.0, 0.0, 0.0), 1.0) * color;
		}
	]])
	volumeMipShader = graphics.newShader([[
#pragma language glsl3
		uniform VolumeImage source;
		vec4 effect(vec4 color, Image unused, vec2 uv, vec2 screen) {
			return textureLod(source, vec3(uv, 0.5), 1.0) * color;
		}
	]])
	replacedCubeShader = graphics.newShader([[
#pragma language glsl3
		uniform CubeImage source;
		vec4 effect(vec4 color, Image unused, vec2 uv, vec2 screen) {
			return textureLod(source, vec3(1.0, 0.0, 0.0), 1.0) * color;
		}
	]])
	replacedVolumeShader = graphics.newShader([[
#pragma language glsl3
		uniform VolumeImage source;
		vec4 effect(vec4 color, Image unused, vec2 uv, vec2 screen) {
			return textureLod(source, vec3(uv, 0.5), 1.0) * color;
		}
	]])
	cubeMipShader:send("source", autoCube)
	volumeMipShader:send("source", autoVolume)
	replacedCubeShader:send("source", replacedCube)
	replacedVolumeShader:send("source", replacedVolume)
	-- The original Love wrapper uses luax_boolflag here, so any non-false Lua
	-- value (including a string) enables mipmaps.
	local truthyMipmaps, truthyImage = pcall(graphics.newImage, data, {mipmaps = "yes"})
	assert(truthyMipmaps and truthyImage)
	canvas = graphics.newCanvas(752, 16, {readable = true})
	print("LOVE_COMPRESSED_IMAGE_BIMG_PASS", width, height, data:getFormat(), data:getSize(),
		"formats=DDS-DXT1+DXT3+DXT5+KTX-DXT1+ASTC4x4+PVR-DXT1+KTX-ETC1+PVR-ETC1+KTX-ETC2rgb+ETC2rgba+ETC2rgba1+PVR-ETC2rgb+ETC2rgba+ETC2rgba1+KTX/PVR-PVRTC1-rgb2+rgb4+rgba2+rgba4+KTX-ASTC5x4+5x5+6x5+6x6+8x5+8x6+8x8+10x5+10x6+10x8+10x10+12x10+12x12+KTX/PVR-EACr+EACrs+EACrg+EACrgs",
		textures[5] and textures[23] and textures[24] and textures[25]
			and textures[26] and textures[27] and textures[28] and textures[29]
			and textures[30] and textures[31] and textures[32] and textures[33]
			and textures[34] and textures[35]
			and "astc-gpu=all14-pass" or "astc-gpu=capability",
		textures[9] and textures[10] and not textures[11]
			and textures[12] and textures[13] and not textures[14]
			and "etc2-gpu=ktx+pvr-rgb+rgba-pass+rgba1-emulation-reject" or "etc2-gpu=capability",
		not textures[15] and textures[16] and not textures[17] and textures[18]
			and not textures[19] and textures[20] and not textures[21] and textures[22]
			and "pvrtc-gpu=ktx+pvr-rgb4+rgba4-pass+2bpp-reject" or "pvrtc-gpu=capability",
		textures[36] and textures[37] and textures[38] and textures[39]
			and textures[40] and textures[41] and textures[42] and textures[43]
			and "eac-gpu=ktx+pvr-all4-pass" or "eac-gpu=capability",
		rendererName == "Metal" and "layered-metal-reject=pass" or "layered-nonmetal-pass=pass",
		"auto-mips=pass")
end

function love.update()
	if rendered then
		local ok, pixels = pcall(canvas.newImageData, canvas)
		if ok then
			assertPixel(pixels, 8, 8, {1, 0, 0}, "compressed 2D base")
			assertPixel(pixels, 24, 8, {1, 0, 0}, "compressed DXT3 base")
			assertPixel(pixels, 40, 8, {1, 0, 0}, "compressed DXT5 base")
			assertPixel(pixels, 56, 8, {1, 0, 0}, "compressed KTX DXT1 base")
			if textures[5] then assertPixel(pixels, 72, 8, {1, 0, 0}, "compressed KTX ASTC base") end
			assertPixel(pixels, 88, 8, {1, 0, 0}, "compressed PVR DXT1 base")
			assertPixel(pixels, 104, 8, {1, 0, 0}, "compressed KTX ETC1 base")
			assertPixel(pixels, 120, 8, {1, 0, 0}, "compressed PVR ETC1 base")
			if textures[9] then assertPixel(pixels, 136, 8, {1, 0, 0}, "compressed KTX ETC2 RGB base") end
			if textures[10] then assertPixel(pixels, 152, 8, {1, 0, 0}, "compressed KTX ETC2 RGBA base") end
			if textures[11] then assertPixel(pixels, 168, 8, {1, 0, 0}, "compressed KTX ETC2 RGBA1 base") end
			if textures[12] then assertPixel(pixels, 184, 8, {1, 0, 0}, "compressed PVR ETC2 RGB base") end
			if textures[13] then assertPixel(pixels, 200, 8, {1, 0, 0}, "compressed PVR ETC2 RGBA base") end
			if textures[14] then assertPixel(pixels, 216, 8, {1, 0, 0}, "compressed PVR ETC2 RGBA1 base") end
			local pvrtcFailures = {}
			for index = 15, 22 do
				if textures[index] then
					local ok, failure = pcall(assertPixel, pixels, (index - 1) * 16 + 8, 8,
						{1, 0, 0}, "compressed PVRTC base " .. index)
					if not ok then pvrtcFailures[#pvrtcFailures + 1] = failure end
				end
			end
			-- Android emulator SwiftShader advertises PVRTC1 but samples its 2bpp
			-- variant as opaque black. Keep the capability/submit coverage there,
			-- while native Metal and every other renderer still require pixel-correct
			-- output for each texture the backend advertises.
			if system.getOS() ~= "Android" then
				assert(#pvrtcFailures == 0, table.concat(pvrtcFailures, "; "))
			end
			for index = 23, 35 do
				if textures[index] then
					assertPixel(pixels, (index - 1) * 16 + 8, 8,
						{1, 0, 0}, "compressed ASTC base " .. index)
				end
			end
			for index = 36, 43 do
				if textures[index] then
					local expected = (index == 38 or index == 39 or index == 42 or index == 43)
						and {1, 1, 0} or {1, 0, 0}
					assertPixel(pixels, (index - 1) * 16 + 8, 8, expected,
						"compressed EAC base " .. index)
				end
			end
			assertPixel(pixels, 696, 8, {0.5, 0, 0.5}, "automatic Cube mip")
			assertPixel(pixels, 712, 8, {0.5, 0, 0.5}, "automatic Volume mip")
			assertPixel(pixels, 728, 8, {0, 1, 0}, "Cube face mip replacement")
			assertPixel(pixels, 744, 8, {1, 1, 0}, "Volume slice mip replacement")
			print("LOVE_COMPRESSED_IMAGE_GPU_PASS", "auto-mip-pixels", "cube-volume-replace")
		else
			assert(rendererName ~= "Metal", pixels)
			assert(tostring(pixels):find("does not support Canvas texture readback", 1, true), pixels)
			print("LOVE_COMPRESSED_IMAGE_GPU_PASS", "submitted", "readback=unsupported")
		end
		assert(love.event.quit())
	end
end

function love.draw()
	if not rendered then
		graphics.setCanvas(canvas)
		graphics.clear(0, 0, 0, 1)
		graphics.setColor(1, 1, 1, 1)
		graphics.draw(textures[1], 0, 0, 0, 4, 4)
		graphics.draw(textures[2], 16, 0, 0, 4, 4)
		graphics.draw(textures[3], 32, 0, 0, 4, 4)
		graphics.draw(textures[4], 48, 0, 0, 4, 4)
		if textures[5] then graphics.draw(textures[5], 64, 0, 0, 4, 4) end
		graphics.draw(textures[6], 80, 0, 0, 4, 4)
		graphics.draw(textures[7], 96, 0, 0, 4, 4)
		graphics.draw(textures[8], 112, 0, 0, 4, 4)
		if textures[9] then graphics.draw(textures[9], 128, 0, 0, 4, 4) end
		if textures[10] then graphics.draw(textures[10], 144, 0, 0, 4, 4) end
		if textures[11] then graphics.draw(textures[11], 160, 0, 0, 4, 4) end
		if textures[12] then graphics.draw(textures[12], 176, 0, 0, 4, 4) end
		if textures[13] then graphics.draw(textures[13], 192, 0, 0, 4, 4) end
		if textures[14] then graphics.draw(textures[14], 208, 0, 0, 4, 4) end
		for index = 15, 22 do
			if textures[index] then
				graphics.draw(textures[index], (index - 1) * 16, 0, 0,
					16 / textures[index]:getWidth(), 16 / textures[index]:getHeight())
			end
		end
		for index = 23, 35 do
			if textures[index] then
				graphics.draw(textures[index], (index - 1) * 16, 0, 0,
					16 / textures[index]:getWidth(), 16 / textures[index]:getHeight())
			end
		end
		for index = 36, 43 do
			if textures[index] then
				graphics.draw(textures[index], (index - 1) * 16, 0, 0, 4, 4)
			end
		end
		graphics.setShader(cubeMipShader)
		graphics.rectangle("fill", 688, 0, 16, 16)
		graphics.setShader(volumeMipShader)
		graphics.rectangle("fill", 704, 0, 16, 16)
		graphics.setShader(replacedCubeShader)
		graphics.rectangle("fill", 720, 0, 16, 16)
		graphics.setShader(replacedVolumeShader)
		graphics.rectangle("fill", 736, 0, 16, 16)
		graphics.setShader()
		graphics.setCanvas()
		rendered = true
	end
end
