import {createRequire} from "node:module";
import path from "node:path";
import {doraSSRRoot} from "./TestPaths.mjs";
import {readFileSync} from "node:fs";

const require = createRequire(import.meta.url);
const ts = require(path.join(doraSSRRoot, "Tools/dora-dora/node_modules/typescript"));
const loveDeclaration = readFileSync(
	path.join(doraSSRRoot, "Assets/Script/Lib/Dora/en/love.d.ts"),
	"utf8",
);

function diagnosticsFor(fileName, source, resolveLove) {
	const files = new Map([[fileName, source]]);
	files.set("/lua.d.ts", "type LuaMultiReturn<T extends unknown[]> = T; type LuaUserdata = { readonly __luaUserdata: unique symbol };");
	if (resolveLove) files.set("/love.d.ts", loveDeclaration);
	const options = {
		strict: true,
		noEmit: true,
		noLib: true,
		module: ts.ModuleKind.CommonJS,
		moduleResolution: ts.ModuleResolutionKind.Classic,
		target: ts.ScriptTarget.ESNext,
		jsx: ts.JsxEmit.Preserve,
	};
	const host = {
		fileExists: name => files.has(name),
		readFile: name => files.get(name),
		getSourceFile: (name, target) => {
			const text = files.get(name);
			return text === undefined ? undefined : ts.createSourceFile(name, text, target, true);
		},
		getDefaultLibFileName: () => "/unused-lib.d.ts",
		writeFile: () => {},
		getCurrentDirectory: () => "/",
		getCanonicalFileName: name => name,
		useCaseSensitiveFileNames: () => true,
		getNewLine: () => "\n",
		resolveModuleNames: moduleNames => moduleNames.map(name => {
			if (resolveLove && name === "love") {
				return {resolvedFileName: "/love.d.ts", extension: ts.Extension.Dts};
			}
			return undefined;
		}),
	};
	return ts.getPreEmitDiagnostics(ts.createProgram([fileName, "/lua.d.ts"], options, host))
		.filter(diagnostic => diagnostic.code !== 2318);
}

const imported = diagnosticsFor("/main.ts", `
	import "love";
	love.conf = config => {
		const version: "11.5" = config.version;
		config.identity = "typed-love";
		config.window.title = "Typed Love";
		config.window.width = 960;
		config.window.height = 540;
		config.window.resizable = true;
		void version;
	};
	love.load = () => {};
	love.update = deltaTime => { const seconds: number = deltaTime; };
	love.graphics.setPointSize(3);
	const pointSize: number = love.graphics.getPointSize();
	const imageFontAtlas = love.image.newImageData(8, 2);
	const imageFont: Love.Font = love.graphics.newImageFont(imageFontAtlas, "A猫", 1, 2);
	const imageRasterizer: Love.Rasterizer = love.font.newImageRasterizer(imageFontAtlas, "A猫");
	const rasterizerFont: Love.Font = love.graphics.newImageFont(imageRasterizer);
	love.graphics.discard([true, false], true);
	love.graphics.flushBatch();
	const graphicsFeatures: Love.GraphicsFeatures = love.graphics.getSupported({sentinel: true});
	const textureTypes: Love.TextureTypes = love.graphics.getTextureTypes();
	const imageFormats: Love.ImageFormats = love.graphics.getImageFormats();
	const rendererInfo: LuaMultiReturn<[string, string, string, string]> = love.graphics.getRendererInfo();
	const supportsGLSL3: boolean = graphicsFeatures.glsl3;
	const supports2DTextures: boolean = textureTypes["2d"];
	const supportsRGBA8Images: boolean = imageFormats.rgba8;
	love.graphics.present();
	void pointSize; void imageFont; void rasterizerFont; void rendererInfo; void supportsGLSL3; void supports2DTextures; void supportsRGBA8Images;
	love.quit = () => false;
	love.event.pump();
	const eventIterator: () => LuaMultiReturn<[string, ...unknown[]] | []> = love.event.poll();
	const eventValues: LuaMultiReturn<[string, ...unknown[]] | []> = eventIterator();
	const waitedEvent: LuaMultiReturn<[string, ...unknown[]] | []> = love.event.wait();
	const eventPushed: boolean = love.event.push("typed", true, 7, "value", undefined);
	love.event.clear();
	const quitQueued: true = love.event.quit(7);
	const restartQueued: true = love.event.quit("restart");
	void eventValues; void waitedEvent; void eventPushed; void quitQueued; void restartQueued;
	love.filesystem.setIdentity("typed-love-save");
	const saveDirectory: string = love.filesystem.getSaveDirectory();
	const workingDirectory: string = love.filesystem.getWorkingDirectory();
	const userDirectory: string = love.filesystem.getUserDirectory();
	const appdataDirectory: string = love.filesystem.getAppdataDirectory();
	const sourceBaseDirectory: string = love.filesystem.getSourceBaseDirectory();
	const executablePath: string = love.filesystem.getExecutablePath();
	const realDirectory: LuaMultiReturn<[string | undefined, string?]> = love.filesystem.getRealDirectory("state.json");
	const requirePath: string = love.filesystem.getRequirePath();
	love.filesystem.setRequirePath("custom/?.lua;" + requirePath);
	const fileInfo: Love.FileInfo | undefined = love.filesystem.getInfo("state.json", "file");
	const legacyExists: boolean = love.filesystem.exists("state.json");
	const legacyDirectory: boolean = love.filesystem.isDirectory("save");
	const legacyFile: boolean = love.filesystem.isFile("state.json");
	const legacySymlink: boolean = love.filesystem.isSymlink("state.json");
	const legacySize: LuaMultiReturn<[number | undefined, string?]> = love.filesystem.getSize("state.json");
	const legacyModified: LuaMultiReturn<[number | undefined, string?]> = love.filesystem.getLastModified("state.json");
	const directoryItems: string[] = love.filesystem.getDirectoryItems();
	const loaded: LuaMultiReturn<[((...args: unknown[]) => unknown) | undefined, string?]> = love.filesystem.load("module.lua");
	const nextLine: () => string | undefined = love.filesystem.lines("notes.txt");
	const file: Love.File = love.filesystem.newFile("state.bin");
	const opened: LuaMultiReturn<[true | undefined, string?]> = file.open("w");
	const fileData: Love.FileData = love.filesystem.newFileData("abc", "state.bin");
	const fileDataImage: Love.Image = love.graphics.newImage(fileData, {mipmaps: false, linear: false, dpiscale: 2});
	void fileDataImage;
	const mountedArchive: boolean = love.filesystem.mount(fileData, "mounted");
	const unmountedArchive: boolean = love.filesystem.unmount(fileData);
	const fused: false = love.filesystem.isFused();
	const joysticks: Love.Joystick[] = love.joystick.getJoysticks();
	const joystick = {} as Love.Joystick;
	if (joysticks) {
		const guid: string = joystick.getGUID();
		const deviceInfo: LuaMultiReturn<[number, number, number]> = joystick.getDeviceInfo();
		const axes: LuaMultiReturn<number[]> = joystick.getAxes();
		const hat: Love.JoystickHat = joystick.getHat(1);
		const vibration: LuaMultiReturn<[number, number]> = joystick.getVibration();
		const connectedIndex: number | undefined = joystick.getConnectedIndex();
		const mapping = joystick.getGamepadMapping("a");
		const mappingString: string | undefined = joystick.getGamepadMappingString();
		joystick.isDown(1, 2); joystick.setVibration(1, 0.5, 0.25); joystick.setVibration();
		love.joystick.setGamepadMapping(guid, "a", "button", 1);
		love.joystick.setGamepadMapping(guid, "dpup", "hat", 1, "u");
		love.joystick.loadGamepadMappings("gamecontrollerdb.txt");
		const savedMappings: string = love.joystick.saveGamepadMappings("mappings.txt");
		const mappingForGuid: string | undefined = love.joystick.getGamepadMappingString(guid);
		void guid; void deviceInfo; void axes; void hat; void vibration; void connectedIndex;
		void mapping; void mappingString; void savedMappings; void mappingForGuid;
	}
	const dataRead: LuaMultiReturn<[Love.FileData | undefined, number | string]> = love.filesystem.read("data", "state.bin");
	file.write(fileData); file.seek(0); file.close();
	const fileMode: Love.FileMode = file.getMode();
	void saveDirectory; void workingDirectory; void userDirectory; void appdataDirectory;
	void sourceBaseDirectory; void realDirectory; void requirePath; void fileInfo; void legacyExists; void legacyDirectory;
	void legacyFile; void legacySymlink; void legacySize; void legacyModified; void directoryItems; void loaded; void nextLine;
	void opened; void dataRead; void fileMode;
	love.keypressed = (key, scancode, isRepeat) => {
		const down: boolean = love.keyboard.isDown(key, scancode);
		const downTable: boolean = love.keyboard.isDown([key, "escape"]);
		const scanDown: boolean = love.keyboard.isScancodeDown(scancode);
		const scanDownTable: boolean = love.keyboard.isScancodeDown([scancode, "escape"]);
		const mappedScan: string = love.keyboard.getScancodeFromKey(key);
		const mappedKey: string = love.keyboard.getKeyFromScancode(scancode);
		love.keyboard.setKeyRepeat(true);
		const repeatEnabled: boolean = love.keyboard.hasKeyRepeat();
		const screenKeyboard: boolean = love.keyboard.hasScreenKeyboard();
		void down; void downTable; void scanDown; void scanDownTable; void mappedScan; void mappedKey;
		void repeatEnabled; void screenKeyboard; void isRepeat;
	};
	love.textinput = text => { const value: string = text; void value; };
	love.mousemoved = (x, y, deltaX, deltaY, isTouch) => {
		const down: boolean = love.mouse.isDown(1, 2);
		const position: LuaMultiReturn<[number, number]> = love.mouse.getPosition();
		void x; void y; void deltaX; void deltaY; void isTouch; void down; void position;
	};
	love.touchpressed = (id, x, y, deltaX, deltaY, pressure) => {
		const touches: Love.TouchID[] = love.touch.getTouches();
		const position: LuaMultiReturn<[number, number]> = love.touch.getPosition(id);
		const currentPressure: number = love.touch.getPressure(id);
		void touches; void position; void currentPressure;
		void x; void y; void deltaX; void deltaY; void pressure;
	};
	love.joystickpressed = (device, button) => {
		const down: boolean = device.isDown(button);
		void down;
	};
	love.joystickreleased = (device, button) => { void device; void button; };
	love.joystickaxis = (device, axis, value) => {
		const current: number = device.getAxis(axis);
		void current; void value;
	};
	love.joystickhat = (device, hatIndex, direction) => {
		const current: Love.JoystickHat = device.getHat(hatIndex);
		const reported: Love.JoystickHat = direction;
		void current; void reported;
	};
	const timerDelta: number = love.timer.getDelta();
	const timerFPS: number = love.timer.getFPS();
	const timerAverage: number = love.timer.getAverageDelta();
	const timerTime: number = love.timer.getTime();
	love.timer.sleep(0);
	void timerDelta; void timerFPS; void timerAverage; void timerTime;
	const systemOS: Love.OS = love.system.getOS();
	const processors: number = love.system.getProcessorCount();
	love.system.setClipboardText("Love clipboard");
	const clipboard: string = love.system.getClipboardText();
	const power: LuaMultiReturn<[Love.PowerState, number | undefined, number | undefined]> = love.system.getPowerInfo();
	const openedURL: boolean = love.system.openURL("https://example.com");
	love.system.vibrate(); love.system.vibrate(0.25);
	const backgroundMusic: boolean = love.system.hasBackgroundMusic();
	void systemOS; void processors; void clipboard; void power; void openedURL; void backgroundMusic;
	const threadChannel: Love.Channel = love.thread.newChannel();
	const namedThreadChannel: Love.Channel = love.thread.getChannel("typed");
	const thread: Love.Thread = love.thread.newThread(file);
	const threadMessageId: number = threadChannel.push(fileData);
	const threadStarted: boolean = thread.start(threadChannel, "typed");
	love.graphics.captureScreenshot(threadChannel);
	void namedThreadChannel; void threadMessageId; void threadStarted;
	const sound: Love.Source = love.audio.newSource("sound.wav", "static");
	const music = love.audio.newSource("music.ogg", "stream");
	const queueData = love.sound.newSoundData(64, 8000, 16, 1);
	const queueSource: Love.Source = love.audio.newQueueableSource(8000, 16, 1, 4);
	const queued: boolean = queueSource.queue(queueData);
	const queuedRegion: boolean = queueSource.queue(queueData, 0, 32);
	const freeBuffers: number = queueSource.getFreeBufferCount();
	sound.setVolume(0.5); sound.setPitch(1.25); sound.setLooping(true); sound.seek(2, "seconds");
	const soundClone: Love.Source = sound.clone();
	const sourceDuration: number = sound.getDuration("seconds");
	const sourceSamples: number = sound.getDuration("samples");
	const sourceChannels: number = sound.getChannelCount();
	const sourceChannelsDeprecated: number = sound.getChannels();
	sound.setPosition(1, 2); sound.setVelocity(3, 4, 5); sound.setDirection(0, 0, -1); sound.setRelative(true);
	sound.setCone(1.5707963267948966, 3.141592653589793, 0.25, 0.5); sound.setAirAbsorption(2); sound.setVolumeLimits(0.1, 0.9);
	sound.setAttenuationDistances(1, 1000); sound.setRolloff(0.75);
	const sourcePosition: LuaMultiReturn<[number, number, number]> = sound.getPosition();
	const sourceVelocity: LuaMultiReturn<[number, number, number]> = sound.getVelocity();
	const sourceDirection: LuaMultiReturn<[number, number, number]> = sound.getDirection();
	const sourceCone: LuaMultiReturn<[number, number, number, number]> = sound.getCone();
	const sourceAirAbsorption: number = sound.getAirAbsorption();
	const sourceVolumeLimits: LuaMultiReturn<[number, number]> = sound.getVolumeLimits();
	const sourceDistances: LuaMultiReturn<[number, number]> = sound.getAttenuationDistances();
	const sourceRelative: boolean = sound.isRelative();
	const sourceRolloff: number = sound.getRolloff();
	sound.seek(2000, "samples");
	const sourceType: Love.SourceType = sound.getType();
	const audioStarted: boolean = love.audio.play(sound, music);
	const audioTableStarted: boolean = love.audio.play([sound, music]);
	const pausedSources: Love.Source[] = love.audio.pause();
	const activeSources: number = love.audio.getActiveSourceCount();
	const activeSourcesDeprecated: number = love.audio.getSourceCount();
	love.audio.setVolume(0.75);
	const audioVolume: number = love.audio.getVolume();
	const mixesWithSystem: boolean = love.audio.setMixWithSystem(true);
	love.audio.setPosition(1, 2); love.audio.setVelocity(3, 4, 5);
	love.audio.setOrientation(0, 0, 1, 0, 1, 0);
	love.audio.setDopplerScale(2);
	const dopplerScale: number = love.audio.getDopplerScale();
	love.audio.setDistanceModel("exponentclamped");
	const distanceModel: Love.DistanceModel = love.audio.getDistanceModel();
	const effectsSupported: boolean = love.audio.isEffectsSupported();
	const maxSceneEffects: number = love.audio.getMaxSceneEffects();
	const maxSourceEffects: number = love.audio.getMaxSourceEffects();
	const recordingDevices: Love.RecordingDevice[] = love.audio.getRecordingDevices();
	const recordingDevice = undefined as unknown as Love.RecordingDevice;
	if (recordingDevices && recordingDevice) {
		const recordingStarted: boolean = recordingDevice.start(8192, 8000, 16, 1);
		const recorded: Love.SoundData | undefined = recordingDevice.getData();
		const stoppedRecording: Love.SoundData | undefined = recordingDevice.stop();
		const recordingSamples: number = recordingDevice.getSampleCount();
		const recordingRate: number = recordingDevice.getSampleRate();
		const recordingDepth: 8 | 16 = recordingDevice.getBitDepth();
		const recordingChannels: 1 | 2 = recordingDevice.getChannelCount();
		const recordingName: string = recordingDevice.getName();
		const isRecording: boolean = recordingDevice.isRecording();
		void recordingStarted; void recorded; void stoppedRecording; void recordingSamples;
		void recordingRate; void recordingDepth; void recordingChannels; void recordingName; void isRecording;
	}
	const effectSet: boolean = love.audio.setEffect("room", {type: "reverb", decaytime: 2, highlimit: true});
	const effectSettings: Love.AudioEffectSettings | undefined = love.audio.getEffect("room");
	const activeEffects: string[] = love.audio.getActiveEffects();
	const filterSet: boolean = sound.setFilter({type: "lowpass", volume: 0.8, highgain: 0.4});
	const filterSettings: Love.AudioFilterSettings | undefined = sound.getFilter();
	const sourceEffectSet: boolean = sound.setEffect("room", {type: "highpass", lowgain: 0.5});
	const sourceEffect: LuaMultiReturn<[boolean, Love.AudioFilterSettings?]> = sound.getEffect("room");
	const sourceEffects: string[] = sound.getActiveEffects();
	const listenerPosition: LuaMultiReturn<[number, number, number]> = love.audio.getPosition();
	const listenerVelocity: LuaMultiReturn<[number, number, number]> = love.audio.getVelocity();
	const listenerOrientation: LuaMultiReturn<[number, number, number, number, number, number]> = love.audio.getOrientation();
	love.audio.pause([sound, music]); love.audio.pause(sound);
	love.audio.stop([sound, music]); love.audio.stop();
	void sourceType; void soundClone; void sourceDuration; void sourceSamples; void sourceChannels;
	void queueSource; void queued; void queuedRegion; void freeBuffers;
	void sourceChannelsDeprecated; void audioStarted; void audioTableStarted; void pausedSources;
	void sourcePosition; void sourceVelocity; void sourceDistances; void sourceRelative; void sourceRolloff;
	void activeSources; void activeSourcesDeprecated; void audioVolume;
	void listenerPosition; void listenerVelocity; void listenerOrientation; void dopplerScale; void distanceModel;
	void effectsSupported; void maxSceneEffects; void maxSourceEffects; void effectSet; void effectSettings; void activeEffects;
	void filterSet; void filterSettings; void sourceEffectSet; void sourceEffect; void sourceEffects;
	love.physics.setMeter(64);
	const physicsMeter: number = love.physics.getMeter();
	const physicsWorld: Love.World = love.physics.newWorld(0, 9.81 * physicsMeter, true);
	const physicsWorldDestroyed: boolean = physicsWorld.isDestroyed();
	physicsWorld.setSleepingAllowed(physicsWorld.isSleepingAllowed());
	const physicsBody: Love.Body = love.physics.newBody(physicsWorld, 100, 40, "dynamic");
	const physicsBodyDestroyed: boolean = physicsBody.isDestroyed();
	const circleShape: Love.CircleShape = love.physics.newCircleShape(12);
	const polygonShape: Love.PolygonShape = love.physics.newRectangleShape(0, 0, 80, 16, 0.25);
	const customPolygon: Love.PolygonShape = love.physics.newPolygonShape([0, 0, 20, 0, 10, 15]);
	const customPolygonVarargs: Love.PolygonShape = love.physics.newPolygonShape(0, 0, 12, 0, 6, 9);
	const edgeShape: Love.EdgeShape = love.physics.newEdgeShape(-20, 0, 20, 0);
	const chainShape: Love.ChainShape = love.physics.newChainShape(false, [-20, 0, 0, -10, 20, 0]);
	const loopChainShape: Love.ChainShape = love.physics.newChainShape(true, 0, 0, 20, 0, 10, 15);
	const chainVertexCount: number = chainShape.getVertexCount();
	const chainPoint: LuaMultiReturn<[number, number]> = loopChainShape.getPoint(4);
	const edgePoints: LuaMultiReturn<[number, number, number, number]> = edgeShape.getPoints();
	const childEdgeShape: Love.EdgeShape = chainShape.getChildEdge(1);
	const childPrevious: LuaMultiReturn<[number, number] | []> = childEdgeShape.getPreviousVertex();
	const childNext: LuaMultiReturn<[number, number] | []> = childEdgeShape.getNextVertex();
	edgeShape.setPreviousVertex(); edgeShape.setNextVertex(30, 0);
	chainShape.setPreviousVertex(-30, 0); chainShape.setNextVertex();
	const polygonValid: boolean = customPolygon.validate() && customPolygonVarargs.validate();
	const physicsFixture: Love.Fixture = love.physics.newFixture(physicsBody, circleShape, 1);
	const physicsFixtureDestroyed: boolean = physicsFixture.isDestroyed();
	physicsFixture.setFriction(0.5); physicsFixture.setRestitution(0.2); physicsFixture.setSensor(false);
	const physicsFixtureType: "circle" | "polygon" | "edge" | "chain" = physicsFixture.getType();
	physicsFixture.setDensity(physicsFixture.getDensity());
	const physicsFixtureBody: Love.Body = physicsFixture.getBody();
	const physicsFixtureShape: Love.Shape = physicsFixture.getShape();
	const physicsFixturePoint: boolean = physicsFixture.testPoint(10, 20);
	const physicsFixtureRay: LuaMultiReturn<[number, number, number] | []> = physicsFixture.rayCast(0, 0, 20, 20, 1);
	physicsFixture.setFilterData(1, 65535, 0);
	const physicsFixtureFilter: LuaMultiReturn<[number, number, number]> = physicsFixture.getFilterData();
	physicsFixture.setCategory(1, 3); physicsFixture.setCategory([1, 3]);
	const physicsFixtureCategories: LuaMultiReturn<number[]> = physicsFixture.getCategory();
	physicsFixture.setMask(2, 4); physicsFixture.setMask([2, 4]);
	const physicsFixtureMask: LuaMultiReturn<number[]> = physicsFixture.getMask();
	physicsFixture.setUserData({kind: "fixture"}); const physicsFixtureData: unknown = physicsFixture.getUserData();
	const physicsFixtureBounds: LuaMultiReturn<[number, number, number, number]> = physicsFixture.getBoundingBox();
	const physicsFixtureMass: LuaMultiReturn<[number, number, number, number]> = physicsFixture.getMassData();
	physicsFixture.setGroupIndex(physicsFixture.getGroupIndex());
	physicsBody.setLinearVelocity(1, 2); physicsBody.applyLinearImpulse(3, 4);
	physicsBody.setX(physicsBody.getX()); physicsBody.setY(physicsBody.getY());
	physicsBody.setTransform(10, 20, 0.5);
	const physicsTransform: LuaMultiReturn<[number, number, number]> = physicsBody.getTransform();
	const physicsWorldPoint: LuaMultiReturn<[number, number]> = physicsBody.getWorldPoint(1, 2);
	const physicsWorldVector: LuaMultiReturn<[number, number]> = physicsBody.getWorldVector(1, 2);
	const physicsWorldPoints: LuaMultiReturn<number[]> = physicsBody.getWorldPoints(1, 2, 3, 4);
	const physicsLocalPoint: LuaMultiReturn<[number, number]> = physicsBody.getLocalPoint(1, 2);
	const physicsLocalVector: LuaMultiReturn<[number, number]> = physicsBody.getLocalVector(1, 2);
	const physicsLocalPoints: LuaMultiReturn<number[]> = physicsBody.getLocalPoints(1, 2, 3, 4);
	const physicsWorldPointVelocity: LuaMultiReturn<[number, number]> = physicsBody.getLinearVelocityFromWorldPoint(1, 2);
	const physicsLocalPointVelocity: LuaMultiReturn<[number, number]> = physicsBody.getLinearVelocityFromLocalPoint(1, 2);
	physicsBody.setAngularVelocity(0.5); physicsBody.setLinearDamping(0.2); physicsBody.setAngularDamping(0.3);
	physicsBody.setFixedRotation(true); physicsBody.applyAngularImpulse(0.1);
	physicsBody.setAwake(physicsBody.isAwake());
	physicsBody.setSleepingAllowed(physicsBody.isSleepingAllowed());
	physicsBody.setActive(physicsBody.isActive());
	physicsBody.setBullet(physicsBody.isBullet());
	physicsBody.setType("kinematic"); physicsBody.setType("dynamic");
	physicsBody.applyForce(4, 5); physicsBody.applyForce(4, 5, 100, 40); physicsBody.applyTorque(0.2);
	const physicsPosition: LuaMultiReturn<[number, number]> = physicsBody.getPosition();
	const physicsAngularVelocity: number = physicsBody.getAngularVelocity();
	const physicsLinearDamping: number = physicsBody.getLinearDamping();
	const physicsAngularDamping: number = physicsBody.getAngularDamping();
	const physicsMass: number = physicsBody.getMass();
	const physicsInertia: number = physicsBody.getInertia();
	const physicsMassData: LuaMultiReturn<[number, number, number, number]> = physicsBody.getMassData();
	physicsBody.setMass(physicsMass); physicsBody.setInertia(physicsInertia);
	physicsBody.setMassData(0, 0, physicsMass, physicsInertia); physicsBody.resetMassData();
	physicsBody.setGravityScale(physicsBody.getGravityScale());
	const physicsLocalCenter: LuaMultiReturn<[number, number]> = physicsBody.getLocalCenter();
	const physicsWorldCenter: LuaMultiReturn<[number, number]> = physicsBody.getWorldCenter();
	const physicsFixedRotation: boolean = physicsBody.isFixedRotation();
	const physicsAwake: boolean = physicsBody.isAwake();
	const physicsSleepingAllowed: boolean = physicsBody.isSleepingAllowed();
	const physicsActive: boolean = physicsBody.isActive();
	const physicsBullet: boolean = physicsBody.isBullet();
	const polygonPoints: LuaMultiReturn<number[]> = polygonShape.getPoints();
	const physicsAnchor = love.physics.newBody(physicsWorld, 0, 0, "static");
	const distanceJoint: Love.DistanceJoint = love.physics.newDistanceJoint(physicsAnchor, physicsBody, 0, 0, 100, 40, false);
	const jointBodies: LuaMultiReturn<[Love.Body, Love.Body]> = distanceJoint.getBodies();
	const jointAnchors: LuaMultiReturn<[number, number, number, number]> = distanceJoint.getAnchors();
	const jointReaction: LuaMultiReturn<[number, number]> = distanceJoint.getReactionForce(60);
	const jointTorque: number = distanceJoint.getReactionTorque(60);
	const collideConnected: boolean = distanceJoint.getCollideConnected();
	distanceJoint.setUserData({tag: "joint"}); const jointData: unknown = distanceJoint.getUserData();
	distanceJoint.setLength(distanceJoint.getLength());
	distanceJoint.setFrequency(distanceJoint.getFrequency());
	distanceJoint.setDampingRatio(distanceJoint.getDampingRatio());
	const physicsJointDestroyed: boolean = distanceJoint.isDestroyed();
	const revoluteJoint: Love.RevoluteJoint = love.physics.newRevoluteJoint(physicsAnchor, physicsBody, 0, 0, 0, 0, false, 0.1);
	const sharedAnchorRevolute: Love.RevoluteJoint = love.physics.newRevoluteJoint(physicsAnchor, physicsBody, 0, 0, false);
	const revoluteAngle: number = revoluteJoint.getJointAngle();
	const revoluteSpeed: number = revoluteJoint.getJointSpeed();
	revoluteJoint.setMotorEnabled(true); const revoluteMotorEnabled: boolean = revoluteJoint.isMotorEnabled();
	revoluteJoint.setMaxMotorTorque(100); const revoluteMaxTorque: number = revoluteJoint.getMaxMotorTorque();
	revoluteJoint.setMotorSpeed(2); const revoluteMotorSpeed: number = revoluteJoint.getMotorSpeed();
	const revoluteTorque: number = revoluteJoint.getMotorTorque(60);
	revoluteJoint.setLimits(-0.5, 0.5); revoluteJoint.setLimitsEnabled(true);
	const revoluteLimits: LuaMultiReturn<[number, number]> = revoluteJoint.getLimits();
	const revoluteLimitsEnabled: boolean = revoluteJoint.areLimitsEnabled();
	const revoluteReference: number = revoluteJoint.getReferenceAngle();
	void sharedAnchorRevolute; void revoluteAngle; void revoluteSpeed; void revoluteMotorEnabled;
	void revoluteMaxTorque; void revoluteMotorSpeed; void revoluteTorque; void revoluteLimits;
	void revoluteLimitsEnabled; void revoluteReference;
	const prismaticJoint: Love.PrismaticJoint = love.physics.newPrismaticJoint(physicsAnchor, physicsBody, 0, 0, 0, 0, 1, 0, false, 0.1);
	const sharedAnchorPrismatic: Love.PrismaticJoint = love.physics.newPrismaticJoint(physicsAnchor, physicsBody, 0, 0, 1, 0, false);
	const prismaticTranslation: number = prismaticJoint.getJointTranslation();
	const prismaticSpeed: number = prismaticJoint.getJointSpeed();
	const prismaticAxis: LuaMultiReturn<[number, number]> = prismaticJoint.getAxis();
	prismaticJoint.setMotorEnabled(true); prismaticJoint.setMaxMotorForce(100);
	prismaticJoint.setMotorSpeed(20); const prismaticForce: number = prismaticJoint.getMotorForce(60);
	prismaticJoint.setLimits(-10, 50); prismaticJoint.setLimitsEnabled(true);
	const prismaticLimits: LuaMultiReturn<[number, number]> = prismaticJoint.getLimits();
	const prismaticReference: number = prismaticJoint.getReferenceAngle();
	void sharedAnchorPrismatic; void prismaticTranslation; void prismaticSpeed; void prismaticAxis;
	void prismaticForce; void prismaticLimits; void prismaticReference;
	const weldJoint: Love.WeldJoint = love.physics.newWeldJoint(physicsAnchor, physicsBody, 0, 0, 1, 1, false, 0.2);
	const sharedAnchorWeld: Love.WeldJoint = love.physics.newWeldJoint(physicsAnchor, physicsBody, 0, 0, false);
	weldJoint.setFrequency(5); weldJoint.setDampingRatio(0.6);
	const weldState: [number, number, number] = [weldJoint.getFrequency(), weldJoint.getDampingRatio(), weldJoint.getReferenceAngle()];
	void sharedAnchorWeld; void weldState;
	const frictionJoint: Love.FrictionJoint = love.physics.newFrictionJoint(physicsAnchor, physicsBody, 0, 0, 1, 1, false);
	const sharedAnchorFriction: Love.FrictionJoint = love.physics.newFrictionJoint(physicsAnchor, physicsBody, 0, 0, false);
	frictionJoint.setMaxForce(100); frictionJoint.setMaxTorque(1000);
	const frictionState: [number, number] = [frictionJoint.getMaxForce(), frictionJoint.getMaxTorque()];
	void sharedAnchorFriction; void frictionState;
	const ropeJoint: Love.RopeJoint = love.physics.newRopeJoint(physicsAnchor, physicsBody, 0, 0, 100, 40, 120, false);
	ropeJoint.setMaxLength(ropeJoint.getMaxLength());
	const ropeType: "distance" | "revolute" | "prismatic" | "weld" | "friction" | "rope" | "pulley" | "wheel" | "mouse" | "motor" | "gear" = ropeJoint.getType();
	void ropeType;
	const pulleyJoint: Love.PulleyJoint = love.physics.newPulleyJoint(physicsAnchor, physicsBody, 0, 0, 100, 0, 0, 40, 100, 60, 2, true);
	const pulleyGround: LuaMultiReturn<[number, number, number, number]> = pulleyJoint.getGroundAnchors();
	const pulleyState: [number, number, number] = [pulleyJoint.getLengthA(), pulleyJoint.getLengthB(), pulleyJoint.getRatio()];
	void pulleyGround; void pulleyState;
	const wheelJoint: Love.WheelJoint = love.physics.newWheelJoint(physicsAnchor, physicsBody, 0, 0, 0, 20, 0, 1, false);
	wheelJoint.setMotorEnabled(true); wheelJoint.setMotorSpeed(2); wheelJoint.setMaxMotorTorque(1000);
	wheelJoint.setSpringFrequency(4); wheelJoint.setSpringDampingRatio(0.5);
	const wheelAxis: LuaMultiReturn<[number, number]> = wheelJoint.getAxis();
	const wheelState: number[] = [wheelJoint.getJointTranslation(), wheelJoint.getJointSpeed(), wheelJoint.getMotorSpeed(), wheelJoint.getMaxMotorTorque(), wheelJoint.getMotorTorque(60), wheelJoint.getSpringFrequency(), wheelJoint.getSpringDampingRatio()];
	void wheelAxis; void wheelState;
	const mouseJoint: Love.MouseJoint = love.physics.newMouseJoint(physicsBody, 0, 0);
	mouseJoint.setTarget(40, 20); mouseJoint.setMaxForce(1000);
	mouseJoint.setFrequency(5); mouseJoint.setDampingRatio(0.7);
	const mouseTarget: LuaMultiReturn<[number, number]> = mouseJoint.getTarget();
	const mouseState: number[] = [mouseJoint.getMaxForce(), mouseJoint.getFrequency(), mouseJoint.getDampingRatio()];
	void mouseTarget; void mouseState;
	const motorJoint: Love.MotorJoint = love.physics.newMotorJoint(physicsAnchor, physicsBody, 0.4, true);
	motorJoint.setLinearOffset(20, 10); motorJoint.setAngularOffset(0.25);
	motorJoint.setMaxForce(1000); motorJoint.setMaxTorque(2000); motorJoint.setCorrectionFactor(0.6);
	const motorOffset: LuaMultiReturn<[number, number]> = motorJoint.getLinearOffset();
	const motorState: number[] = [motorJoint.getAngularOffset(), motorJoint.getMaxForce(), motorJoint.getMaxTorque(), motorJoint.getCorrectionFactor()];
	void motorOffset; void motorState;
	const gearJoint: Love.GearJoint = love.physics.newGearJoint(revoluteJoint, prismaticJoint, 2, true);
	gearJoint.setRatio(-2);
	const gearSources: LuaMultiReturn<[Love.RevoluteJoint | Love.PrismaticJoint, Love.RevoluteJoint | Love.PrismaticJoint]> = gearJoint.getJoints();
	const gearRatio: number = gearJoint.getRatio();
	void gearSources; void gearRatio;
	const beginContact: Love.ContactCallback = (fixtureA, fixtureB, contact) => {
		const fixtures: LuaMultiReturn<[Love.Fixture, Love.Fixture]> = contact.getFixtures();
		const children: LuaMultiReturn<[number, number]> = contact.getChildren();
		const positions: LuaMultiReturn<number[]> = contact.getPositions();
		const normal: LuaMultiReturn<[number, number]> = contact.getNormal();
		contact.setFriction(contact.getFriction()); contact.resetFriction();
		contact.setRestitution(contact.getRestitution()); contact.resetRestitution();
		contact.setTangentSpeed(contact.getTangentSpeed()); contact.setEnabled(contact.isEnabled());
		const valid: boolean = contact.isValid(); const touching: boolean = contact.isTouching();
		void fixtureA; void fixtureB; void fixtures; void children; void positions; void normal; void valid; void touching;
	};
	const postSolve: Love.PostSolveCallback = (fixtureA, fixtureB, contact, ...impulses) => {
		void fixtureA; void fixtureB; void contact; void impulses;
	};
	physicsWorld.setCallbacks(beginContact, undefined, beginContact, postSolve);
	const contactCallbacks: LuaMultiReturn<[Love.ContactCallback | undefined, Love.ContactCallback | undefined,
		Love.ContactCallback | undefined, Love.PostSolveCallback | undefined]> = physicsWorld.getCallbacks();
	physicsWorld.queryBoundingBox(0, 0, 200, 200, fixture => fixture === physicsFixture);
	physicsWorld.rayCast(0, 0, 200, 200, (fixture, x, y, normalX, normalY, fraction) => {
		const hitFixture: Love.Fixture = fixture;
		void hitFixture; void x; void y; void normalX; void normalY;
		return fraction;
	});
	physicsWorld.update(1 / 60, 8, 3);
	if (false) { distanceJoint.destroy(); physicsFixture.destroy(); physicsBody.destroy(); physicsWorld.destroy(); }
	void physicsPosition; void polygonPoints; void jointBodies; void jointAnchors; void jointReaction;
	void jointTorque; void collideConnected; void jointData; void contactCallbacks; void physicsMassData;
	void physicsWorldDestroyed; void physicsBodyDestroyed; void physicsFixtureDestroyed; void physicsJointDestroyed;
	void physicsFixtureType; void physicsFixtureBody; void physicsFixtureShape; void physicsFixturePoint;
	void physicsFixtureRay; void physicsFixtureFilter; void physicsFixtureCategories; void physicsFixtureMask;
	void physicsFixtureData; void physicsFixtureBounds; void physicsFixtureMass;
	void chainVertexCount; void chainPoint; void edgePoints; void childPrevious; void childNext; void polygonValid;
	const soundData: Love.SoundData = love.sound.newSoundData(128, 22050, 16, 2);
	soundData.setSample(0, 1, 0.5);
	const sampleValue: number = soundData.getSample(0, 1);
	const soundDuration: number = soundData.getDuration();
	const decodedSoundData: Love.SoundData = love.sound.newSoundData(fileData);
	const decoder: Love.Decoder = love.sound.newDecoder(fileData, 4096);
	const decodedChunk: Love.SoundData | undefined = decoder.decode();
	decoder.seek(0);
	const expandedDecoder: Love.SoundData = love.sound.newSoundData(decoder);
	const pcmSource: Love.Source = love.audio.newSource(soundData);
	void sampleValue; void soundDuration; void decodedSoundData; void decoder; void decodedChunk; void expandedDecoder; void pcmSource;
	const randomGenerator: Love.RandomGenerator = love.math.newRandomGenerator(1, 2);
	const randomValue: number = randomGenerator.random(1, 6);
	const randomSeed: LuaMultiReturn<[number, number]> = randomGenerator.getSeed();
	randomGenerator.setState(randomGenerator.getState());
	const randomTriangles: number[][] = love.math.triangulate([0, 0, 1, 0, 0, 1]);
	const byteColor: LuaMultiReturn<[number, number, number, number?]> = love.math.colorToBytes(1, 0.5, 0);
	const noiseValue: number = love.math.noise(0.25, 0.5, 0.75);
	const transform: Love.Transform = love.math.newTransform(1, 2);
	const transformedPoint: LuaMultiReturn<[number, number]> = transform.transformPoint(3, 4);
	const curve: Love.BezierCurve = love.math.newBezierCurve([0, 0, 10, 20, 20, 0]);
	const curvePoint: LuaMultiReturn<[number, number]> = curve.evaluate(0.5);
	const byteData: Love.ByteData = love.data.newByteData("abcdef");
	const loveObjectType: string = byteData.type();
	const loveObjectIsData: boolean = byteData.typeOf("Data");
	const loveObjectReleased: boolean = love.data.newByteData("release-me").release();
	const dataView: Love.DataView = love.data.newDataView(byteData, 1, 4);
	const encodedData: Love.ByteData = love.data.encode("data", "base64", dataView);
	const encodedString: string = love.data.encode("string", "hex", byteData);
	const compressedData: Love.CompressedData = love.data.compress("data", "zlib", encodedData);
	const decompressedData: Love.ByteData = love.data.decompress("data", compressedData);
	const packedData: Love.ByteData = love.data.pack("data", "<I2", 7);
	const unpackedData: LuaMultiReturn<any[]> = love.data.unpack("<I2", packedData);
	const packedSize: number = love.data.getPackedSize("<I2");
	const legacyCompressed: Love.CompressedData = love.math.compress("data", "gzip", byteData);
	void randomValue; void randomSeed; void randomTriangles; void byteColor; void noiseValue; void transformedPoint; void curvePoint;
	void encodedString; void decompressedData; void unpackedData; void packedSize; void legacyCompressed;
	const layer = love.image.newImageData(2, 2);
	const glyphAtlas = love.image.newImageData(8, 2);
	const rasterizer: Love.Rasterizer = love.font.newImageRasterizer(glyphAtlas, "A猫", 2, 1);
	const glyphData: Love.GlyphData = love.font.newGlyphData(rasterizer, "A");
	const glyphDimensions: LuaMultiReturn<[number, number]> = glyphData.getDimensions();
	const glyphBytes: Love.ByteData = love.data.newByteData(glyphData);
	const hasGlyphs: boolean = rasterizer.hasGlyphs("A", 0x732b);
	const trueTypeRasterizer: Love.Rasterizer = love.font.newTrueTypeRasterizer("font.ttf", 18, "normal", 1);
	const defaultRasterizer: Love.Rasterizer = love.font.newRasterizer(16, "none", 1);
	const bmRasterizer: Love.Rasterizer = love.font.newBMFontRasterizer(fileData, [glyphAtlas], 1);
	const glyphFormat: "rgba8" | "la8" = trueTypeRasterizer.getGlyphData("A").getFormat();
	void glyphDimensions; void glyphBytes; void hasGlyphs; void defaultRasterizer; void bmRasterizer; void glyphFormat;
	const arrayImage: Love.Image = love.graphics.newArrayImage([layer, layer], {mipmaps: false});
	const arrayQuad = love.graphics.newQuad(0, 0, 1, 1, 2, 2);
	love.graphics.drawLayer(arrayImage, 2, 3, 4);
	love.graphics.drawLayer(arrayImage, 1, arrayQuad, 5, 6);
	const cubeImage = love.graphics.newCubeImage([layer, layer, layer, layer, layer, layer]);
	const volumeImage = love.graphics.newVolumeImage([layer, layer]);
	const textureType: Love.TextureType = arrayImage.getTextureType();
	const layerCount: number = arrayImage.getLayerCount();
	const depth: number = volumeImage.getDepth();
	void cubeImage; void arrayQuad; void textureType; void layerCount; void depth;
	const batchImage = love.graphics.newImage("batch.png");
	const batchQuad = love.graphics.newQuad(0, 0, 8, 8, batchImage);
	const spriteBatch: Love.SpriteBatch = love.graphics.newSpriteBatch(batchImage, 16, "dynamic");
	const spriteIndex: number = spriteBatch.add(batchQuad, 10, 20);
	spriteBatch.set(spriteIndex, batchQuad, 20, 30);
	spriteBatch.setColor(1, 0.5, 0.25, 1);
	spriteBatch.setDrawRange(1, 1); spriteBatch.flush();
	const batchCount: number = spriteBatch.getCount();
	const batchTexture: Love.Image | Love.Canvas = spriteBatch.getTexture();
	love.graphics.draw(spriteBatch, 0, 0);
	void batchCount; void batchTexture;
	const shader: Love.Shader = love.graphics.newShader("shader.frag");
	shader.send("mask", love.graphics.newImage("fixture.png"));
	shader.send("overlay", love.graphics.newCanvas(8, 8));
	shader.send("layers", love.graphics.newImage("fixture.png"), love.graphics.newCanvas(8, 8));
	shader.sendColor("tint", [1, 0.5, 0]);
	shader.send("intensity", 1);
	shader.send("enabled", true);
	shader.send("weights", 0.25, 0.5, 1);
	shader.send("offsets", [2, -2], [4, -4]);
	shader.send("gates", [true, false], [false, true]);
	shader.send("basis", [1, 2, 3, 4]);
	shader.send("frames", "column", [[1, 2, 3], [4, 5, 6], [7, 8, 9]]);
	shader.send("packed", fileData, 0, 16);
	shader.send("packedMatrix", "row", fileData, 0, 16);
	shader.send("packedMatrix", fileData, "column", 0, 16);
	shader.sendColor("packedColor", fileData, 0, 16);
	const shaderWarnings: string = shader.getWarnings();
	const shaderHasTint: boolean = shader.hasUniform("tint");
	const shaderValidation: LuaMultiReturn<[boolean, string?]> = love.graphics.validateShader(false, fileData);
	love.graphics.setShader(shader);
	const activeShader: Love.Shader | undefined = love.graphics.getShader();
	love.graphics.setShader();
	void shaderWarnings; void shaderHasTint; void shaderValidation; void activeShader;
	love.draw = () => {
		love.graphics.push();
		const stackDepth: number = love.graphics.getStackDepth();
		love.graphics.setBackgroundColor([0, 0, 0, 1]);
		const background: LuaMultiReturn<[number, number, number, number]> = love.graphics.getBackgroundColor();
		love.graphics.setDefaultFilter("nearest", "nearest", 2);
		const defaultFilter: LuaMultiReturn<[Love.FilterMode, Love.FilterMode, number]> = love.graphics.getDefaultFilter();
		love.graphics.setLineStyle("rough");
		const lineStyle: Love.LineStyle = love.graphics.getLineStyle();
		love.graphics.setLineJoin("bevel");
		const lineJoin: Love.LineJoin = love.graphics.getLineJoin();
		love.graphics.setWireframe(true);
		const wireframe: boolean = love.graphics.isWireframe();
		const graphicsActive: boolean = love.graphics.isActive();
		const gammaCorrect: boolean = love.graphics.isGammaCorrect();
		love.graphics.setBlendMode("add", "alphamultiply");
		const blend: LuaMultiReturn<[Love.BlendMode, Love.BlendAlphaMode]> = love.graphics.getBlendMode();
		love.graphics.setScissor(10, 20, 100, 50);
		love.graphics.intersectScissor(20, 20, 50, 25);
		love.graphics.setScissor();
		love.graphics.setColorMask(true, true, true, false);
		const colorMask: LuaMultiReturn<[boolean, boolean, boolean, boolean]> = love.graphics.getColorMask();
		love.graphics.setColorMask();
		love.graphics.stencil(() => love.graphics.rectangle("fill", 0, 0, 10, 10), "replace", 1);
		love.graphics.setStencilTest("equal", 1);
		const stencilTest: LuaMultiReturn<[Love.CompareMode, number]> = love.graphics.getStencilTest();
		love.graphics.setStencilTest();
		void stackDepth; void background; void defaultFilter; void lineStyle; void lineJoin; void graphicsActive; void gammaCorrect; void blend;
		void colorMask;
		void stencilTest;
		love.graphics.translate(10, 20);
		love.graphics.rotate(0.5);
		love.graphics.scale(2);
		love.graphics.shear(0.1, 0.2);
		const graphicsTransform = love.math.newTransform(2, 3);
		love.graphics.applyTransform(graphicsTransform);
		love.graphics.replaceTransform(graphicsTransform);
		const graphicsPoint: LuaMultiReturn<[number, number]> = love.graphics.transformPoint(1, 2);
		const inverseGraphicsPoint: LuaMultiReturn<[number, number]> = love.graphics.inverseTransformPoint(3, 5);
		void graphicsPoint; void inverseGraphicsPoint;
		love.graphics.polygon("fill", 0, 0, 10, 0, 0, 10);
		love.graphics.ellipse("line", 20, 20, 10, 5);
		const font = love.graphics.newFont(20);
		love.graphics.setFont(font);
		const fontWidth: number = font.getWidth("hello");
		const fontHeight: number = font.getHeight();
		const baseline: number = font.getBaseline();
		const wrapped: LuaMultiReturn<[number, string[]]> = font.getWrap("hello world", 60);
		love.graphics.print("hello", 10, 20);
		love.graphics.printf("hello world", 10, 50, 100, "center");
		void fontWidth; void fontHeight; void baseline; void wrapped;
		const image = love.graphics.newImage("pig.png");
		const canvas: Love.Canvas = love.graphics.newCanvas(128, 64, {dpiscale: 1, msaa: 0, format: "rgba8", type: "2d", readable: true, mipmaps: "none"});
		const hdrCanvas: Love.Canvas = love.graphics.newCanvas(128, 64, {msaa: 4, format: "hdr", readable: true});
		const depthStencilCanvas: Love.Canvas = love.graphics.newCanvas(128, 64, {format: "depth24stencil8", readable: false});
		const canvasFormats: Love.CanvasFormats = love.graphics.getCanvasFormats(true);
		const canvasDimensions: LuaMultiReturn<[number, number]> = canvas.getPixelDimensions();
		const canvasReadback: Love.ImageData = canvas.newImageData(1, 1, 0, 0, 16, 8);
		canvas.setFilter("nearest"); canvas.setWrap("clamp");
		love.graphics.setCanvas(canvas);
		const currentCanvas: Love.Canvas | LuaMultiReturn<[Love.Canvas, ...Love.Canvas[]]> | Love.CanvasSetup | undefined = love.graphics.getCanvas();
		love.graphics.setCanvas([canvas]);
		const canvasSetup = [canvas] as Love.CanvasSetup;
		canvasSetup.depth = true;
		canvasSetup.stencil = true;
		canvasSetup.depthstencil = depthStencilCanvas;
		love.graphics.setCanvas(canvasSetup);
		love.graphics.setCanvas();
		const imageData: Love.ImageData = love.image.newImageData(2, 2, "rgba8");
		const nativeImageData: Love.ImageData = love.image.newImageData(2, 2, "rgba16f");
		const nativeFormat: Love.ImagePixelFormat = nativeImageData.getFormat();
		const encodedTga: Love.FileData = nativeImageData.encode("tga");
		imageData.setPixel(0, 0, 1, 0.5, 0, 1);
		const imagePixel: LuaMultiReturn<[number, number, number, number]> = imageData.getPixel(0, 0);
		const imageDataDimensions: LuaMultiReturn<[number, number]> = imageData.getDimensions();
		const imageDataType: "ImageData" = imageData.type();
		const imageDataIsData: boolean = imageData.typeOf("Data");
		const uploadedImage: Love.Image = love.graphics.newImage(imageData, {mipmaps: false});
		uploadedImage.replacePixels(imageData, 1, 1, 0, 0, false);
		const uploadedImageType: "Image" = uploadedImage.type();
		const uploadedImageIsTexture: boolean = uploadedImage.typeOf("Texture");
		const canvasType: "Canvas" = canvas.type();
		const canvasIsTexture: boolean = canvas.typeOf("Texture");
		const systemLimits: Love.GraphicsSystemLimits = love.graphics.getSystemLimits({sentinel: true});
		const textureSize: number = systemLimits.texturesize;
		love.graphics.getStats({sentinel: true}).drawcalls;
		const clonedImageData: Love.ImageData = imageData.clone();
		const decodedImageData: Love.ImageData = love.image.newImageData(love.filesystem.newFileData("pig.png"));
		const compressedImageData: Love.CompressedImageData = love.image.newCompressedData(love.filesystem.newFileData("texture.dds"));
		const compressedDimensions: LuaMultiReturn<[number, number]> = compressedImageData.getDimensions(1);
		const compressedFormat: Love.CompressedPixelFormat = compressedImageData.getFormat();
		const compressedProbe: boolean = love.image.isCompressed(compressedImageData);
		const compressedTexture: Love.Image = love.graphics.newImage(compressedImageData, {mipmaps: true});
		const quad: Love.Quad = love.graphics.newQuad(0, 0, 16, 16, image);
		const canvasQuad: Love.Quad = love.graphics.newQuad(0, 0, 16, 16, canvas);
		const numericQuad: Love.Quad = love.graphics.newQuad(0, 0, 16, 16, 32, 32);
		const viewport: LuaMultiReturn<[number, number, number, number]> = quad.getViewport();
		quad.setViewport(8, 8, 16, 16); quad.setLayer(1);
		const width: number = image.getWidth();
		image.setFilter("nearest");
		const filter: LuaMultiReturn<[Love.FilterMode, Love.FilterMode, number]> = image.getFilter();
		const wrappedTexture: boolean = image.setWrap("repeat", "mirroredrepeat", "clampzero");
		const textureWrap: LuaMultiReturn<[Love.WrapMode, Love.WrapMode, Love.WrapMode]> = image.getWrap();
		love.graphics.draw(image, quad, 20, 30, 0.2, 2, 2, 8, 8);
		love.graphics.draw(image, width, 20, 0.2, 0.5, 0.5, 16, 16);
		love.graphics.draw(canvas, canvasQuad, 0, 0);
		const mode: LuaMultiReturn<[number, number, Love.WindowMode]> = love.window.getMode();
		const resized: boolean = love.window.setMode(480, 270, {resizable: true});
		const updatedSettings: boolean = love.window.updateMode({resizable: false});
		const updatedSize: boolean = love.window.updateMode(512, 288, {resizable: true});
		const dpi: number = love.window.getDPIScale();
		const nativeDpi: number = love.window.getNativeDPIScale();
		const graphicsDpi: number = love.graphics.getDPIScale();
		const pixelDimensions: LuaMultiReturn<[number, number]> = love.graphics.getPixelDimensions();
		const pixelWidth: number = love.graphics.getPixelWidth();
		const pixelHeight: number = love.graphics.getPixelHeight();
		love.graphics.captureScreenshot("capture.png");
		love.graphics.captureScreenshot(captured => {
			const capturedWidth: number = captured.getWidth();
			void capturedWidth;
		});
		const pixelScalar: number = love.window.toPixels(12.5);
		const pixels: LuaMultiReturn<[number, number]> = love.window.toPixels(12.5, 4);
		const logicalScalar: number = love.window.fromPixels(12.5);
		const logical: LuaMultiReturn<[number, number]> = love.window.fromPixels(12.5, 4);
		void canvasDimensions; void canvasReadback; void hdrCanvas; void canvasFormats; void currentCanvas; void imagePixel; void imageDataDimensions; void imageDataType; void imageDataIsData;
		void uploadedImage; void uploadedImageType; void uploadedImageIsTexture; void canvasType; void canvasIsTexture; void systemLimits; void textureSize; void clonedImageData; void decodedImageData;
		void compressedDimensions; void compressedFormat; void compressedProbe; void compressedTexture;
		void numericQuad; void viewport; void filter; void wrappedTexture; void textureWrap; void mode; void resized; void updatedSettings; void updatedSize; void dpi; void nativeDpi;
		void graphicsDpi; void pixelDimensions; void pixelWidth; void pixelHeight; void pixelScalar; void pixels; void logicalScalar; void logical;
		love.graphics.pop();
		love.graphics.reset();
	};
`, true);
if (imported.length !== 0) {
	throw new Error(`imported Love declaration diagnostics: ${imported.map(d => `${d.code}: ${ts.flattenDiagnosticMessageText(d.messageText, " ")}`).join("; ")}`);
}

const tsx = diagnosticsFor("/main.tsx", `
	import "love";
	love.draw = () => {};
`, true);
if (tsx.length !== 0) {
	throw new Error(`TSX Love declaration diagnostics: ${tsx.map(d => d.code).join(", ")}`);
}

const ordinaryDoraFile = diagnosticsFor("/ordinary.ts", "love.draw = () => {};", false);
if (!ordinaryDoraFile.some(diagnostic => diagnostic.code === 2304)) {
	throw new Error("ordinary TypeScript file unexpectedly received the Love global declaration");
}

console.log("PASS: import-triggered Love definitions, ordinary TS isolation, standard TSX checking");
