-- [ts]: UIX.ts
local ____exports = {} -- 1
local ____types = require("UIX.types") -- 1
local defaultInteractionState = ____types.defaultInteractionState -- 1
local mergeInteractionState = ____types.mergeInteractionState -- 1
local clamp = ____types.clamp -- 1
local ____theme = require("UIX.theme") -- 2
local doraPrismTheme = ____theme.doraPrismTheme -- 2
local mergeTheme = ____theme.mergeTheme -- 2
local ____context = require("UIX.context") -- 3
local getUiContext = ____context.getUiContext -- 3
local UiProvider = ____context.UiProvider -- 3
local ThemeScope = ____context.ThemeScope -- 3
local ____FocusManager = require("UIX.input.FocusManager") -- 4
local FocusManager = ____FocusManager.FocusManager -- 4
local ____Interaction = require("UIX.input.Interaction") -- 5
local useInteraction = ____Interaction.useInteraction -- 5
local ____PaintNode = require("UIX.paint.PaintNode") -- 6
local PaintNode = ____PaintNode.PaintNode -- 6
local ____color = require("UIX.paint.color") -- 7
local withAlpha = ____color.withAlpha -- 7
local mixColor = ____color.mixColor -- 7
local ____clip = require("UIX.paint.clip") -- 8
local registerClip = ____clip.registerClip -- 8
local unregisterClip = ____clip.unregisterClip -- 8
local applyAncestorClips = ____clip.applyAncestorClips -- 8
local ____primitives = require("UIX.paint.primitives") -- 9
local rect = ____primitives.rect -- 9
local roundedPanel = ____primitives.roundedPanel -- 9
local buttonSurface = ____primitives.buttonSurface -- 9
local progressTrack = ____primitives.progressTrack -- 9
local progressFill = ____primitives.progressFill -- 9
local focusRing = ____primitives.focusRing -- 9
local cooldownMask = ____primitives.cooldownMask -- 9
local itemSlotSurface = ____primitives.itemSlotSurface -- 9
local ____icons = require("UIX.paint.icons") -- 10
local iconPainters = ____icons.iconPainters -- 10
local drawIcon = ____icons.drawIcon -- 10
local ____Box = require("UIX.layout.Box") -- 11
local Box = ____Box.Box -- 11
local ____Row = require("UIX.layout.Row") -- 12
local Row = ____Row.Row -- 12
local ____Column = require("UIX.layout.Column") -- 13
local Column = ____Column.Column -- 13
local ____Stack = require("UIX.layout.Stack") -- 14
local Stack = ____Stack.Stack -- 14
local ____Spacer = require("UIX.layout.Spacer") -- 15
local Spacer = ____Spacer.Spacer -- 15
local ____Panel = require("UIX.layout.Panel") -- 16
local Panel = ____Panel.Panel -- 16
local ____ScrollView = require("UIX.layout.ScrollView") -- 17
local ScrollView = ____ScrollView.ScrollView -- 17
local ____Text = require("UIX.foundation.Text") -- 18
local Text = ____Text.Text -- 18
local wrapTextLines = ____Text.wrapTextLines -- 18
local ____Icon = require("UIX.foundation.Icon") -- 19
local Icon = ____Icon.Icon -- 19
local ____FocusRing = require("UIX.foundation.FocusRing") -- 20
local FocusRing = ____FocusRing.FocusRing -- 20
local ____Button = require("UIX.controls.Button") -- 21
local Button = ____Button.Button -- 21
local ____IconButton = require("UIX.controls.IconButton") -- 22
local IconButton = ____IconButton.IconButton -- 22
local ____ProgressBar = require("UIX.controls.ProgressBar") -- 23
local ProgressBar = ____ProgressBar.ProgressBar -- 23
local ____Slider = require("UIX.controls.Slider") -- 24
local Slider = ____Slider.Slider -- 24
local ____Tabs = require("UIX.controls.Tabs") -- 25
local Tabs = ____Tabs.Tabs -- 25
local ____Toggle = require("UIX.controls.Toggle") -- 26
local Toggle = ____Toggle.Toggle -- 26
local ____Checkbox = require("UIX.controls.Checkbox") -- 27
local Checkbox = ____Checkbox.Checkbox -- 27
local ____RadioGroup = require("UIX.controls.RadioGroup") -- 28
local RadioGroup = ____RadioGroup.RadioGroup -- 28
local ____Select = require("UIX.controls.Select") -- 29
local Select = ____Select.Select -- 29
local ____TextInput = require("UIX.controls.TextInput") -- 30
local TextInput = ____TextInput.TextInput -- 30
local ____Stepper = require("UIX.controls.Stepper") -- 31
local Stepper = ____Stepper.Stepper -- 31
local ____Tooltip = require("UIX.overlay.Tooltip") -- 32
local Tooltip = ____Tooltip.Tooltip -- 32
local ____Modal = require("UIX.overlay.Modal") -- 33
local Modal = ____Modal.Modal -- 33
local ____ToastStack = require("UIX.overlay.ToastStack") -- 34
local ToastStack = ____ToastStack.ToastStack -- 34
local ____HealthBar = require("UIX.game.HealthBar") -- 35
local HealthBar = ____HealthBar.HealthBar -- 35
local ____ResourceCounter = require("UIX.game.ResourceCounter") -- 36
local ResourceCounter = ____ResourceCounter.ResourceCounter -- 36
local ____CooldownButton = require("UIX.game.CooldownButton") -- 37
local CooldownButton = ____CooldownButton.CooldownButton -- 37
local ____ItemSlot = require("UIX.game.ItemSlot") -- 38
local ItemSlot = ____ItemSlot.ItemSlot -- 38
local ____InventoryGrid = require("UIX.game.InventoryGrid") -- 39
local InventoryGrid = ____InventoryGrid.InventoryGrid -- 39
____exports.defaultInteractionState = defaultInteractionState -- 42
____exports.mergeInteractionState = mergeInteractionState -- 43
____exports.clamp = clamp -- 44
____exports.doraPrismTheme = doraPrismTheme -- 45
____exports.mergeTheme = mergeTheme -- 46
____exports.getUiContext = getUiContext -- 47
____exports.UiProvider = UiProvider -- 48
____exports.ThemeScope = ThemeScope -- 49
____exports.FocusManager = FocusManager -- 50
____exports.useInteraction = useInteraction -- 51
____exports.PaintNode = PaintNode -- 52
____exports.withAlpha = withAlpha -- 53
____exports.mixColor = mixColor -- 54
____exports.registerClip = registerClip -- 55
____exports.unregisterClip = unregisterClip -- 56
____exports.applyAncestorClips = applyAncestorClips -- 57
____exports.rect = rect -- 58
____exports.roundedPanel = roundedPanel -- 59
____exports.buttonSurface = buttonSurface -- 60
____exports.progressTrack = progressTrack -- 61
____exports.progressFill = progressFill -- 62
____exports.focusRing = focusRing -- 63
____exports.cooldownMask = cooldownMask -- 64
____exports.itemSlotSurface = itemSlotSurface -- 65
____exports.iconPainters = iconPainters -- 66
____exports.drawIcon = drawIcon -- 67
____exports.Box = Box -- 68
____exports.Row = Row -- 69
____exports.Column = Column -- 70
____exports.Stack = Stack -- 71
____exports.Spacer = Spacer -- 72
____exports.Panel = Panel -- 73
____exports.ScrollView = ScrollView -- 74
____exports.Text = Text -- 75
____exports.wrapTextLines = wrapTextLines -- 76
____exports.Icon = Icon -- 77
____exports.FocusRing = FocusRing -- 78
____exports.Button = Button -- 79
____exports.IconButton = IconButton -- 80
____exports.ProgressBar = ProgressBar -- 81
____exports.Slider = Slider -- 82
____exports.Tabs = Tabs -- 83
____exports.Toggle = Toggle -- 84
____exports.Checkbox = Checkbox -- 85
____exports.RadioGroup = RadioGroup -- 86
____exports.Select = Select -- 87
____exports.TextInput = TextInput -- 88
____exports.Stepper = Stepper -- 89
____exports.Tooltip = Tooltip -- 90
____exports.Modal = Modal -- 91
____exports.ToastStack = ToastStack -- 92
____exports.HealthBar = HealthBar -- 93
____exports.ResourceCounter = ResourceCounter -- 94
____exports.CooldownButton = CooldownButton -- 95
____exports.ItemSlot = ItemSlot -- 96
____exports.InventoryGrid = InventoryGrid -- 97
return ____exports -- 97